services:
  php-fpm:
    build: .
    volumes:
      - ./../../../VMA-Work/rst-acs:/srv/rst-acs
  server:
    image: nginx:1.25-alpine
    volumes:
      - ./../../../VMA-Work/rst-acs:/srv/rst-acs
      - ./acs-nginx.conf:/etc/nginx/conf.d/acs-nginx.conf
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - acs-data:/var/lib/mysql
    ports:
      - "3300:3306"
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass nwfQPGPnoxW6L69hRsb304hp7MOC
    volumes:
      - acs-redis:/data

volumes:
  acs-data:
  acs-redis:
