services:
  php80-fpm:
    build: ./php/80
    volumes:
      - ./../../../VMA-Work/idp:/srv/idp
      - ./../../../VMA-Work/rst-acs:/srv/rst-acs
      - db-data:/var/lib/mysql-data
  php82-fpm:
    build: ./php/82
    volumes:
      - ./../../../VMA-Work/idp-symfony:/srv/idp-symfony
      - ./../../../VMA-Work/simplesamlphp:/srv/simplesamlphp
      - db-data:/var/lib/mysql-data
  php81-fpm:
    build: ./php/81
    volumes:
      - db-data:/var/lib/mysql-data
  nginx:
    image: nginx:1.27.4-alpine
    volumes:
      - ./../../../VMA-Work/idp-symfony:/srv/idp-symfony
      - ./nginx/vhost/idp-symfony.conf:/etc/nginx/conf.d/idp-symfony.conf
      - ./../../../VMA-Work/idp:/srv/idp
      - ./nginx/vhost/idp.conf:/etc/nginx/conf.d/idp-nginx.conf
      - ./../../../VMA-Work/rst-acs:/srv/rst-acs
      - ./nginx/vhost/acs-nginx.conf:/etc/nginx/conf.d/acs-nginx.conf
      - ./../../../VMA-Work/simplesamlphp:/srv/simplesamlphp
      - ./nginx/vhost/simplesamlphp.conf:/etc/nginx/conf.d/simplesamlphp.conf
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - idp-local.rschooltoday.test
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    command:
      - --require_secure_transport=ON
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - MySQL_Server_8.0.42_Auto_Generated_Server_Certificate
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass nwfQPGPnoxW6L69hRsb304hp7MOC
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
