services:
  web:
    build:
      context: .
    container_name: test-wp-web
    volumes:
      - ./test-wp:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: test-wp-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - test-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: test-wp-pma
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
volumes:
  test-data:
