services:
#  web:
#    build:
#      context: .
#    container_name: test-wp-web
#    volumes:
#      - ./test-wp:/var/www/html
#    ports:
#      - 9000:80
#    environment:
#      - DB_HOST=db
#      - DB_NAME=test_wp_db
#      - DB_USER=root
#      - DB_PASSWORD=secret
#    depends_on:
#      - db
  db:
    image: mysql:latest
#    container_name: test-wp-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
#    volumes:
#      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
#    container_name: test-wp-pma
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
#volumes:
#  db-data:
