services:
#  web:
#    build:
#      context: .
#    container_name: test-wp-web
#    volumes:
#      - ./test-wp:/var/www/html
#    ports:
#      - 9000:80
  db:
    image: mysql:latest
    container_name: test-wp-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  #  volumes:
  #    - db-data:/var/lib/mysql
  #  networks:
  #    - test-wp-network
  phpmyadmin:
    image: phpmyadmin
    container_name: test-wp-pma
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
#    networks:
#      - test-wp-network
    depends_on:
      - db
#volumes:
#  db-data:
#networks:
#  test-wp-network:
