services:
  web:
    build:
      context: .
    container_name: test-wp-web
    volumes:
      - ./test-wp:/var/www/html
    ports:
      - 9000:80
  db:
    image: mysql:latest
    container_name: test-wp-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - wp-db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: test-wp-pma
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
volumes:
  wp-db-data:
