server {
  listen 80;
  listen [::]:80;

  server_name fs-local.rschooltoday.test;

  index index.php index.html;

  error_log /var/log/nginx/fs-local.rschooltoday.test-error.log;

  access_log /var/log/nginx/fs-local.rschooltoday.test-access.log;

  root /srv/facility-scheduler/docroot;

  location /app/ {
      alias /srv/facility-scheduler/application/;
  }

  location /cad_js/ {
      alias /srv/facility-scheduler/lib/Scripts/;
  }

  location /yui/ {
      alias /srv/facility-scheduler/lib/Scripts/Yui/build/;
  }

  location /cad_clients/ {
      alias /srv/facility-scheduler/clients/;
  }

  location /lib/ {        
    alias /srv/facility-scheduler/lib/;
  }

  location / {
      try_files $uri $uri/ /index.php?$query_string;
      gzip_static on;
  }

  location ~ \.php$ {
      include fastcgi_params;
      try_files $uri =404;
      fastcgi_pass php-fpm:9000;

      fastcgi_index index.php;
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO $fastcgi_path_info;
  }

  location ^~ /simplesaml {
    alias /srv/facility-scheduler/lib/Tools/simplesamlphp/public;

    # the prefix must match the baseurlpath configuration option
    location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
      include fastcgi_params;
      fastcgi_pass php-fpm:9000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$phpfile;

      # must be prepended with the baseurlpath
      fastcgi_param SCRIPT_NAME /simplesaml$phpfile;

      fastcgi_param PATH_INFO $pathinfo if_not_empty;
    }
  }

  location ~ /\.ht {
      deny all;
  }

}