services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ../../rst-acs:/srv/rst-acs
      - ./rst-acs.conf:/etc/nginx/conf.d/rst-acs.conf
    ports:
      - "80:80"

  php-fpm:
    build:
      context: .
    volumes:
      - ../../rst-acs:/srv/rst-acs
      - db-data:/var/lib/mysql

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command:
      - --require_secure_transport=ON
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      default:
        aliases:
          - MySQL_Server_8.4.10_Auto_Generated_Server_Certificate

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass nwfQPGPnoxW6L69hRsb304hp7MOC
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: