#!/bin/sh
docker run \
        --network=host \
        --rm \
        -e HOME="$HOME" \
        -u $(id -u):$(id -g) \
        -v "$HOME/VMA-Work/rst-acs":"$HOME/VMA-Work/rst-acs" \
        -w "$PWD" \
        php:8.1-alpine \
        php "$@"

exit $?
