server {
  listen 80;
  listen [::]:80;

  server_name tr-local.rschooltoday.test;

  index index.php index.html;

  error_log /var/log/nginx/tr-local.rschooltoday.test-error.log;

  access_log /var/log/nginx/tr-local.rschooltoday.test-access.log;

  root /srv/tr-new/www;

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location /app {        
    alias /srv/tr-new/app/www;
  } 

  location ~ \.php$ {
      include fastcgi_params;
      try_files $uri =404;
      fastcgi_pass php-fpm:9000;

      fastcgi_index index.php;
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO $fastcgi_path_info;
  }

  location ~ /\.ht {
    deny all;
  }

}